version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000